#!/bin/bash

/bin/echo "Installer 0.1"

cd /usr/share/kbd/keymaps/i386 && ls */*.map.gz
/bin/echo ""
/bin/echo -n "Write the name of the keyboard layout you want to use, then press [ENTER]: "
read keymap
/bin/echo `Chosen keymap: $keymap` && cd 
/bin/loadkeys $keymap || echo "ERROR: Wrong keyboard layout"; exit 1